export const getAllAnnoucementsOptions = {
  id: true,
  banner: true,
  brand: true,
  color: true,
  comments: true,
  createdAt: true,
  description: true,
  fuelType: true,
  images: true,
  isActive: true,
  isGoodBuy: true,
  mileage: true,
  model: true,
  price: true,
  priceFipe: true,
  updatedAt: true,
  year: true,
  user: {
    select: {
      id: true,
      name: true,
      email: true,
      cpf: true,
      accountType: true,
      birthdate: true,
      description: true,
      avatar: true,
      phone: true,
      createdAt: true,
      updatedAt: true,
      address: true,
    },
  },
};
