export const responseBodyUser = {
  id: true,
  name: true,
  email: true,
  cpf: true,
  accountType: true,
  birthdate: true,
  description: true,
  avatar: true,
  phone: true,
  createdAt: true,
  updatedAt: true,
  address: true,
  announcements: true,
  comments: true,
};
